version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: nala_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpw         # root user password
      MYSQL_DATABASE: mysql_db            # auto-create database
      MYSQL_USER: nala_user               # project user
      MYSQL_PASSWORD: nala_pw             # project user password
    ports:
      - "3306:3306"                       # expose MySQL on localhost:3306
    volumes:
      - mysql_data:/var/lib/mysql         # persist data locally
      
volumes:
  mysql_data:
